-- ONE ROW PER CHARGE. `member_subscription` is a "who subscribed and when"
-- ledger — a plan switch ends one row and starts another, and it holds no
-- payment state at all — so nothing in the app could say whether an outlet or an
-- agency had ever PAID. Both Subscription screens could only list what the org
-- was on, which is why their "history" was really a trail of plan switches.
--
-- One row per billing period per subscription: agency WEEKLY (Sun-Sat, the same
-- payroll week the whole app uses), outlet MONTHLY (anchored on the day the
-- subscription started, clamped to month length). Generated by
-- `subscription-invoice.repository.generateMissing`, which is idempotent — the
-- unique index below is what makes it so, and is the only thing standing between
-- a re-run and a double charge.
--
-- Who / which plan are read through `member_subscription_id`; no name is copied.
-- `amount` and `currency` ARE snapshotted, deliberately: a Custom price
-- renegotiated in September must not rewrite what August was billed.
--
-- `status` defaults to 'unpaid' and only an admin moves it. Nothing in this app
-- can observe a bank transfer, so there is no automatic transition to 'paid'.
DO $$ BEGIN
 CREATE TYPE "main"."subscription_invoice_status" AS ENUM('unpaid', 'paid');
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "main"."subscription_invoice" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"member_subscription_id" uuid NOT NULL,
	"period_start" date NOT NULL,
	"period_end" date NOT NULL,
	"amount" numeric(12, 2) NOT NULL,
	"currency" varchar(8) DEFAULT 'MYR' NOT NULL,
	"status" "main"."subscription_invoice_status" DEFAULT 'unpaid' NOT NULL,
	"paid_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" varchar DEFAULT 'system' NOT NULL,
	"updated_by" varchar DEFAULT 'system' NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "main"."subscription_invoice" ADD CONSTRAINT "subscription_invoice_member_subscription_id_fk" FOREIGN KEY ("member_subscription_id") REFERENCES "main"."member_subscription"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
-- The idempotency guarantee: one invoice per subscription per period, so a
-- second generator run inserts nothing instead of billing the period twice.
CREATE UNIQUE INDEX IF NOT EXISTS "subscription_invoice_subscription_period_idx"
  ON "main"."subscription_invoice" ("member_subscription_id","period_start");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_invoice_status_idx"
  ON "main"."subscription_invoice" ("status");
