/**
 * Writes the backend's copy of the landing-chat facts from the ONE source,
 * apps/web/src/components/landing/handoff/landing-chat-knowledge.ts.
 *
 *   pnpm chat:facts         rewrite the generated file
 *   pnpm chat:facts:check   exit 1 while the generated file is stale
 *
 * Same idea as `rbac:sync`: the backend must build the AI's prompt itself (a
 * caller could otherwise send the model its own "facts"), and a hand-kept copy
 * would drift — so the copy is generated and checked, never edited.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { allFactSheets } from "../../apps/web/src/components/landing/handoff/landing-chat-knowledge.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const target = resolve(root, "apps/backend/src/features/landing-chat/landing-chat-facts.generated.ts");

const source = [
  "// GENERATED by `pnpm chat:facts` from",
  "// apps/web/src/components/landing/handoff/landing-chat-knowledge.ts — DO NOT EDIT.",
  "// Edit the answers there, then run `pnpm chat:facts`.",
  "",
  `export const LANDING_CHAT_FACTS = ${JSON.stringify(allFactSheets(), null, 2)} as const;`,
  "",
].join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8").replace(/\r\n/g, "\n");
  } catch {
    /* missing counts as stale */
  }
  if (current !== source) {
    console.error("landing-chat facts are STALE — run `pnpm chat:facts` and commit the result.");
    process.exit(1);
  }
  console.log("landing-chat facts are up to date.");
} else {
  writeFileSync(target, source);
  console.log(`wrote ${target} (${source.length.toLocaleString()} chars)`);
}
