/**
 * Writes the backend's copy of the landing-chat facts from the ONE source,
 * apps/web/src/components/landing/handoff/landing-chat-knowledge.ts, plus the
 * system sections built from the code (landing-chat-system-facts.mts: menus,
 * team permissions, the database's tables, TEST_SCRIPT §11 What's new).
 *
 *   pnpm chat:facts         rewrite the generated file
 *   pnpm chat:facts:check   exit 1 while the generated file is stale (CI runs it)
 *
 * Same idea as `rbac:sync`: the backend must build the AI's prompt itself (a
 * caller could otherwise send the model its own "facts"), and a hand-kept copy
 * would drift — so the copy is generated and checked, never edited. Because the
 * system sections are read from the code, a new table, newly checked permission,
 * menu page or What's-new row makes `--check` fail until the facts are
 * regenerated. ⚠️ CI runs it on pull requests only (not on a direct push to
 * main), and a running backend must reload to pick up the new file.
 *
 * Both modes refuse facts that fail the public-safety scan (public-safety.ts):
 * they are sent to an outside model and shown to anonymous visitors.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describeFindings, scanPublicText } from "../../apps/backend/src/features/landing-chat/public-safety.ts";
import { allFactSheets } from "../../apps/web/src/components/landing/handoff/landing-chat-knowledge.ts";
import { buildSystemSections } from "./landing-chat-system-facts.mts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const target = resolve(root, "apps/backend/src/features/landing-chat/landing-chat-facts.generated.ts");

let system: ReturnType<typeof buildSystemSections>;
try {
  system = buildSystemSections(root);
} catch (err) {
  console.error(`landing-chat facts NOT written — ${(err as Error).message}`);
  process.exit(1);
}
const sheets = allFactSheets(system);

/* The finding names the rule and the section heading, never the matched text. */
const unsafe: string[] = [];
for (const [locale, byRole] of Object.entries(sheets)) {
  for (const [role, text] of Object.entries(byRole)) {
    const findings = scanPublicText(text);
    if (findings.length === 0) continue;
    const headings = [
      ...new Set(findings.map((f) => text.slice(0, f.offset).split("\n## ").pop()?.split("\n")[0] ?? "")),
    ].slice(0, 5);
    unsafe.push(`${locale}/${role}: ${describeFindings(findings)} — in: ${headings.join(" | ")}`);
  }
}
if (unsafe.length > 0) {
  console.error(
    `landing-chat facts NOT written — they carry what the public chat must never publish:\n  · ${unsafe.join("\n  · ")}`,
  );
  process.exit(1);
}

const source = [
  "// GENERATED by `pnpm chat:facts` from",
  "// apps/web/src/components/landing/handoff/landing-chat-knowledge.ts and the system",
  "// sections tools/scripts/landing-chat-system-facts.mts reads from the code — DO NOT EDIT.",
  "// Edit the answers or landing-chat-system.ts, then run `pnpm chat:facts`.",
  "",
  `export const LANDING_CHAT_FACTS = ${JSON.stringify(sheets, null, 2)} as const;`,
  "",
].join("\n");

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8").replace(/\r\n/g, "\n");
  } catch {
    /* missing counts as stale */
  }
  if (current !== source) {
    console.error("landing-chat facts are STALE — run `pnpm chat:facts` and commit the result.");
    process.exit(1);
  }
  console.log(`landing-chat facts are up to date (${system.length} system sections, public-safety clean).`);
} else {
  writeFileSync(target, source);
  console.log(
    `wrote ${target} (${source.length.toLocaleString()} chars, ${system.length} system sections, public-safety clean)`,
  );
}
