/**
 * Admin divisions (state / province / region) for IMI-allowed signup countries.
 * Keyed by country display name (same strings as NATIONALITY_OPTIONS).
 * Malaysia keeps the curated MY list used elsewhere in the app.
 */
export const STATES_BY_COUNTRY: Record<string, readonly string[]> = {
	Malaysia: [
		'Johor',
		'Kedah',
		'Kelantan',
		'Malacca',
		'Negeri Sembilan',
		'Pahang',
		'Penang',
		'Perak',
		'Perlis',
		'Sabah',
		'Sarawak',
		'Selangor',
		'Terengganu',
		'Kuala Lumpur',
		'Labuan',
		'Putrajaya',
	],
	Indonesia: [
		'Aceh',
		'Bali',
		'Banten',
		'Bengkulu',
		'DI Yogyakarta',
		'DKI Jakarta',
		'Gorontalo',
		'Jambi',
		'Jawa Barat',
		'Jawa Tengah',
		'Jawa Timur',
		'Kalimantan Barat',
		'Kalimantan Selatan',
		'Kalimantan Tengah',
		'Kalimantan Timur',
		'Kalimantan Utara',
		'Kepulauan Bangka Belitung',
		'Kepulauan Riau',
		'Lampung',
		'Maluku',
		'Maluku Utara',
		'Nusa Tenggara Barat',
		'Nusa Tenggara Timur',
		'Papua',
		'Papua Barat',
		'Papua Barat Daya',
		'Papua Pegunungan',
		'Papua Selatan',
		'Papua Tengah',
		'Riau',
		'Sulawesi Barat',
		'Sulawesi Selatan',
		'Sulawesi Tengah',
		'Sulawesi Tenggara',
		'Sulawesi Utara',
		'Sumatera Barat',
		'Sumatera Selatan',
		'Sumatera Utara',
	],
	Thailand: [
		'Amnat Charoen',
		'Ang Thong',
		'Bangkok',
		'Bueng Kan',
		'Buriram',
		'Chachoengsao',
		'Chai Nat',
		'Chaiyaphum',
		'Chanthaburi',
		'Chiang Mai',
		'Chiang Rai',
		'Chonburi',
		'Chumphon',
		'Kalasin',
		'Kamphaeng Phet',
		'Kanchanaburi',
		'Khon Kaen',
		'Krabi',
		'Lampang',
		'Lamphun',
		'Loei',
		'Lopburi',
		'Mae Hong Son',
		'Maha Sarakham',
		'Mukdahan',
		'Nakhon Nayok',
		'Nakhon Pathom',
		'Nakhon Phanom',
		'Nakhon Ratchasima',
		'Nakhon Sawan',
		'Nakhon Si Thammarat',
		'Nan',
		'Narathiwat',
		'Nong Bua Lamphu',
		'Nong Khai',
		'Nonthaburi',
		'Pathum Thani',
		'Pattani',
		'Phang Nga',
		'Phatthalung',
		'Phayao',
		'Phetchabun',
		'Phetchaburi',
		'Phichit',
		'Phitsanulok',
		'Phra Nakhon Si Ayutthaya',
		'Phrae',
		'Phuket',
		'Prachinburi',
		'Prachuap Khiri Khan',
		'Ranong',
		'Ratchaburi',
		'Rayong',
		'Roi Et',
		'Sa Kaeo',
		'Sakon Nakhon',
		'Samut Prakan',
		'Samut Sakhon',
		'Samut Songkhram',
		'Saraburi',
		'Satun',
		'Sing Buri',
		'Sisaket',
		'Songkhla',
		'Sukhothai',
		'Suphan Buri',
		'Surat Thani',
		'Surin',
		'Tak',
		'Trang',
		'Treat',
		'Ubon Ratchathani',
		'Udon Thani',
		'Uthai Thani',
		'Uttaradit',
		'Yala',
		'Yasothon',
	],
	Cambodia: [
		'Banteay Meanchey',
		'Battambang',
		'Kampong Cham',
		'Kampong Chhnang',
		'Kampong Speu',
		'Kampong Thom',
		'Kampot',
		'Kandal',
		'Koh Kong',
		'Kratié',
		'Mondulkiri',
		'Oddar Meanchey',
		'Pailin',
		'Phnom Penh',
		'Preah Sihanouk',
		'Preah Vihear',
		'Prey Veng',
		'Pursat',
		'Ratanakiri',
		'Siem Reap',
		'Stung Treng',
		'Svay Rieng',
		'Takéo',
		'Tboung Khmum',
		'Kep',
	],
	Bangladesh: [
		'Barishal',
		'Chattogram',
		'Dhaka',
		'Khulna',
		'Mymensingh',
		'Rajshahi',
		'Rangpur',
		'Sylhet',
	],
	Myanmar: [
		'Ayeyarwady',
		'Bago',
		'Chin',
		'Kachin',
		'Kayah',
		'Kayin',
		'Magway',
		'Mandalay',
		'Mon',
		'Naypyidaw',
		'Rakhine',
		'Sagaing',
		'Shan',
		'Tanintharyi',
		'Yangon',
	],
	Laos: [
		'Attapeu',
		'Bokeo',
		'Bolikhamsai',
		'Champasak',
		'Houaphanh',
		'Khammouane',
		'Luang Namtha',
		'Luang Prabang',
		'Oudomxay',
		'Phongsaly',
		'Sainyabuli',
		'Salavan',
		'Savannakhet',
		'Sekong',
		'Vientiane Prefecture',
		'Vientiane Province',
		'Xaisomboun',
		'Xiangkhouang',
	],
	Vietnam: [
		'An Giang',
		'Bà Rịa - Vũng Tàu',
		'Bắc Giang',
		'Bắc Kạn',
		'Bạc Liêu',
		'Bắc Ninh',
		'Bến Tre',
		'Bình Định',
		'Bình Dương',
		'Bình Phước',
		'Bình Thuận',
		'Cà Mau',
		'Cần Thơ',
		'Cao Bằng',
		'Đà Nẵng',
		'Đắk Lắk',
		'Đắk Nông',
		'Điện Biên',
		'Đồng Nai',
		'Đồng Tháp',
		'Gia Lai',
		'Hà Giang',
		'Hà Nam',
		'Hà Nội',
		'Hà Tĩnh',
		'Hải Dương',
		'Hải Phòng',
		'Hậu Giang',
		'Hòa Bình',
		'Hưng Yên',
		'Khánh Hòa',
		'Kiên Giang',
		'Kon Tum',
		'Lai Châu',
		'Lâm Đồng',
		'Lạng Sơn',
		'Lào Cai',
		'Long An',
		'Nam Định',
		'Nghệ An',
		'Ninh Bình',
		'Ninh Thuận',
		'Phú Thọ',
		'Phú Yên',
		'Quảng Bình',
		'Quảng Nam',
		'Quảng Ngãi',
		'Quảng Ninh',
		'Quảng Trị',
		'Sóc Trăng',
		'Sơn La',
		'Tây Ninh',
		'Thái Bình',
		'Thái Nguyên',
		'Thanh Hóa',
		'Thừa Thiên Huế',
		'Tiền Giang',
		'TP Hồ Chí Minh',
		'Trà Vinh',
		'Tuyên Quang',
		'Vĩnh Long',
		'Vĩnh Phúc',
		'Yên Bái',
	],
	Pakistan: [
		'Azad Jammu and Kashmir',
		'Balochistan',
		'Gilgit-Baltistan',
		'Islamabad Capital Territory',
		'Khyber Pakhtunkhwa',
		'Punjab',
		'Sindh',
	],
	'Sri Lanka': [
		'Central',
		'Eastern',
		'North Central',
		'Northern',
		'North Western',
		'Sabaragamuwa',
		'Southern',
		'Uva',
		'Western',
	],
	Turkmenistan: [
		'Ahal',
		'Ashgabat',
		'Balkan',
		'Dashoguz',
		'Lebap',
		'Mary',
	],
	Uzbekistan: [
		'Andijan',
		'Bukhara',
		'Fergana',
		'Jizzakh',
		'Karakalpakstan',
		'Namangan',
		'Navoiy',
		'Qashqadaryo',
		'Samarqand',
		'Sirdaryo',
		'Surxondaryo',
		'Tashkent City',
		'Tashkent Region',
		'Xorazm',
	],
	Kazakhstan: [
		'Abai',
		'Akmola',
		'Aktobe',
		'Almaty',
		'Almaty City',
		'Atyrau',
		'East Kazakhstan',
		'Jambyl',
		'Jetisu',
		'Karaganda',
		'Kostanay',
		'Kyzylorda',
		'Mangystau',
		'North Kazakhstan',
		'Pavlodar',
		'Shymkent',
		'Turkistan',
		'Ulytau',
		'West Kazakhstan',
		'Astana',
	],
	Nepal: [
		'Koshi',
		'Madhesh',
		'Bagmati',
		'Gandaki',
		'Lumbini',
		'Karnali',
		'Sudurpaschim',
	],
	Philippines: [
		'Abra',
		'Agusan del Norte',
		'Agusan del Sur',
		'Aklan',
		'Albay',
		'Antique',
		'Apayao',
		'Aurora',
		'Basilan',
		'Bataan',
		'Batanes',
		'Batangas',
		'Benguet',
		'Biliran',
		'Bohol',
		'Bukidnon',
		'Bulacan',
		'Cagayan',
		'Camarines Norte',
		'Camarines Sur',
		'Camiguin',
		'Capiz',
		'Catanduanes',
		'Cavite',
		'Cebu',
		'Cotabato',
		'Davao de Oro',
		'Davao del Norte',
		'Davao del Sur',
		'Davao Occidental',
		'Davao Oriental',
		'Dinagat Islands',
		'Eastern Samar',
		'Guimaras',
		'Ifugao',
		'Ilocos Norte',
		'Ilocos Sur',
		'Iloilo',
		'Isabela',
		'Kalinga',
		'La Union',
		'Laguna',
		'Lanao del Norte',
		'Lanao del Sur',
		'Leyte',
		'Maguindanao del Norte',
		'Maguindanao del Sur',
		'Marinduque',
		'Masbate',
		'Metro Manila',
		'Misamis Occidental',
		'Misamis Oriental',
		'Mountain Province',
		'Negros Occidental',
		'Negros Oriental',
		'Northern Samar',
		'Nueva Ecija',
		'Nueva Vizcaya',
		'Occidental Mindoro',
		'Oriental Mindoro',
		'Palawan',
		'Pampanga',
		'Pangasinan',
		'Quezon',
		'Quirino',
		'Rizal',
		'Romblon',
		'Samar',
		'Sarangani',
		'Siquijor',
		'Sorsogon',
		'South Cotabato',
		'Southern Leyte',
		'Sultan Kudarat',
		'Sulu',
		'Surigao del Norte',
		'Surigao del Sur',
		'Tarlac',
		'Tawi-Tawi',
		'Zambales',
		'Zamboanga del Norte',
		'Zamboanga del Sur',
		'Zamboanga Sibugay',
	],
	India: [
		'Andaman and Nicobar Islands',
		'Andhra Pradesh',
		'Arunachal Pradesh',
		'Assam',
		'Bihar',
		'Chandigarh',
		'Chhattisgarh',
		'Dadra and Nagar Haveli and Daman and Diu',
		'Delhi',
		'Goa',
		'Gujarat',
		'Haryana',
		'Himachal Pradesh',
		'Jammu and Kashmir',
		'Jharkhand',
		'Karnataka',
		'Kerala',
		'Ladakh',
		'Lakshadweep',
		'Madhya Pradesh',
		'Maharashtra',
		'Manipur',
		'Meghalaya',
		'Mizoram',
		'Nagaland',
		'Odisha',
		'Puducherry',
		'Punjab',
		'Rajasthan',
		'Sikkim',
		'Tamil Nadu',
		'Telangana',
		'Tripura',
		'Uttar Pradesh',
		'Uttarakhand',
		'West Bengal',
	],
};

/** States/provinces for a country display name, or empty if unknown. */
export function statesForCountry(countryName: string): readonly string[] {
	return STATES_BY_COUNTRY[countryName] ?? [];
}
