/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as adminSettingsRouteImport } from './routes/(admin)/settings'
import { Route as adminProfileRouteImport } from './routes/(admin)/profile'
import { Route as adminDashboardRouteImport } from './routes/(admin)/dashboard'
import { Route as adminUserManagementRouteRouteImport } from './routes/(admin)/user-management/route'
import { Route as adminRbacRouteRouteImport } from './routes/(admin)/rbac/route'
import { Route as adminBusinessRouteRouteImport } from './routes/(admin)/business/route'
import { Route as adminAuditLogRouteRouteImport } from './routes/(admin)/audit-log/route'
import { Route as adminAuditLogIndexRouteImport } from './routes/(admin)/audit-log/index'
import { Route as adminUserManagementPrRouteImport } from './routes/(admin)/user-management/pr'
import { Route as adminUserManagementOutletRouteImport } from './routes/(admin)/user-management/outlet'
import { Route as adminUserManagementAgencyRouteImport } from './routes/(admin)/user-management/agency'
import { Route as adminUserManagementAdminRouteImport } from './routes/(admin)/user-management/admin'
import { Route as adminServiceRequestsRouteImport } from './routes/(admin)/service/requests'
import { Route as adminServiceOtherRouteImport } from './routes/(admin)/service/other'
import { Route as adminRbacRoleRouteImport } from './routes/(admin)/rbac/role'
import { Route as adminRbacPermissionRouteImport } from './routes/(admin)/rbac/permission'
import { Route as adminRbacModuleRouteImport } from './routes/(admin)/rbac/module'
import { Route as adminBusinessSubscriptionRouteImport } from './routes/(admin)/business/subscription'
import { Route as adminBusinessPlanRouteImport } from './routes/(admin)/business/plan'
import { Route as adminBusinessHistoryRouteImport } from './routes/(admin)/business/history'
import { Route as adminAuditLogRoleRouteImport } from './routes/(admin)/audit-log/$role'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const adminSettingsRoute = adminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminProfileRoute = adminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminDashboardRoute = adminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminUserManagementRouteRoute =
  adminUserManagementRouteRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => adminRouteRoute,
  } as any)
const adminRbacRouteRoute = adminRbacRouteRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminBusinessRouteRoute = adminBusinessRouteRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAuditLogRouteRoute = adminAuditLogRouteRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAuditLogIndexRoute = adminAuditLogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminAuditLogRouteRoute,
} as any)
const adminUserManagementPrRoute = adminUserManagementPrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => adminUserManagementRouteRoute,
} as any)
const adminUserManagementOutletRoute =
  adminUserManagementOutletRouteImport.update({
    id: '/outlet',
    path: '/outlet',
    getParentRoute: () => adminUserManagementRouteRoute,
  } as any)
const adminUserManagementAgencyRoute =
  adminUserManagementAgencyRouteImport.update({
    id: '/agency',
    path: '/agency',
    getParentRoute: () => adminUserManagementRouteRoute,
  } as any)
const adminUserManagementAdminRoute =
  adminUserManagementAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => adminUserManagementRouteRoute,
  } as any)
const adminServiceRequestsRoute = adminServiceRequestsRouteImport.update({
  id: '/service/requests',
  path: '/service/requests',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminServiceOtherRoute = adminServiceOtherRouteImport.update({
  id: '/service/other',
  path: '/service/other',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminRbacRoleRoute = adminRbacRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => adminRbacRouteRoute,
} as any)
const adminRbacPermissionRoute = adminRbacPermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => adminRbacRouteRoute,
} as any)
const adminRbacModuleRoute = adminRbacModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => adminRbacRouteRoute,
} as any)
const adminBusinessSubscriptionRoute =
  adminBusinessSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => adminBusinessRouteRoute,
  } as any)
const adminBusinessPlanRoute = adminBusinessPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => adminBusinessRouteRoute,
} as any)
const adminBusinessHistoryRoute = adminBusinessHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => adminBusinessRouteRoute,
} as any)
const adminAuditLogRoleRoute = adminAuditLogRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => adminAuditLogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/audit-log': typeof adminAuditLogRouteRouteWithChildren
  '/business': typeof adminBusinessRouteRouteWithChildren
  '/rbac': typeof adminRbacRouteRouteWithChildren
  '/user-management': typeof adminUserManagementRouteRouteWithChildren
  '/dashboard': typeof adminDashboardRoute
  '/profile': typeof adminProfileRoute
  '/settings': typeof adminSettingsRoute
  '/audit-log/$role': typeof adminAuditLogRoleRoute
  '/business/history': typeof adminBusinessHistoryRoute
  '/business/plan': typeof adminBusinessPlanRoute
  '/business/subscription': typeof adminBusinessSubscriptionRoute
  '/rbac/module': typeof adminRbacModuleRoute
  '/rbac/permission': typeof adminRbacPermissionRoute
  '/rbac/role': typeof adminRbacRoleRoute
  '/service/other': typeof adminServiceOtherRoute
  '/service/requests': typeof adminServiceRequestsRoute
  '/user-management/admin': typeof adminUserManagementAdminRoute
  '/user-management/agency': typeof adminUserManagementAgencyRoute
  '/user-management/outlet': typeof adminUserManagementOutletRoute
  '/user-management/pr': typeof adminUserManagementPrRoute
  '/audit-log/': typeof adminAuditLogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/business': typeof adminBusinessRouteRouteWithChildren
  '/rbac': typeof adminRbacRouteRouteWithChildren
  '/user-management': typeof adminUserManagementRouteRouteWithChildren
  '/dashboard': typeof adminDashboardRoute
  '/profile': typeof adminProfileRoute
  '/settings': typeof adminSettingsRoute
  '/audit-log/$role': typeof adminAuditLogRoleRoute
  '/business/history': typeof adminBusinessHistoryRoute
  '/business/plan': typeof adminBusinessPlanRoute
  '/business/subscription': typeof adminBusinessSubscriptionRoute
  '/rbac/module': typeof adminRbacModuleRoute
  '/rbac/permission': typeof adminRbacPermissionRoute
  '/rbac/role': typeof adminRbacRoleRoute
  '/service/other': typeof adminServiceOtherRoute
  '/service/requests': typeof adminServiceRequestsRoute
  '/user-management/admin': typeof adminUserManagementAdminRoute
  '/user-management/agency': typeof adminUserManagementAgencyRoute
  '/user-management/outlet': typeof adminUserManagementOutletRoute
  '/user-management/pr': typeof adminUserManagementPrRoute
  '/audit-log': typeof adminAuditLogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/(admin)/audit-log': typeof adminAuditLogRouteRouteWithChildren
  '/(admin)/business': typeof adminBusinessRouteRouteWithChildren
  '/(admin)/rbac': typeof adminRbacRouteRouteWithChildren
  '/(admin)/user-management': typeof adminUserManagementRouteRouteWithChildren
  '/(admin)/dashboard': typeof adminDashboardRoute
  '/(admin)/profile': typeof adminProfileRoute
  '/(admin)/settings': typeof adminSettingsRoute
  '/(admin)/audit-log/$role': typeof adminAuditLogRoleRoute
  '/(admin)/business/history': typeof adminBusinessHistoryRoute
  '/(admin)/business/plan': typeof adminBusinessPlanRoute
  '/(admin)/business/subscription': typeof adminBusinessSubscriptionRoute
  '/(admin)/rbac/module': typeof adminRbacModuleRoute
  '/(admin)/rbac/permission': typeof adminRbacPermissionRoute
  '/(admin)/rbac/role': typeof adminRbacRoleRoute
  '/(admin)/service/other': typeof adminServiceOtherRoute
  '/(admin)/service/requests': typeof adminServiceRequestsRoute
  '/(admin)/user-management/admin': typeof adminUserManagementAdminRoute
  '/(admin)/user-management/agency': typeof adminUserManagementAgencyRoute
  '/(admin)/user-management/outlet': typeof adminUserManagementOutletRoute
  '/(admin)/user-management/pr': typeof adminUserManagementPrRoute
  '/(admin)/audit-log/': typeof adminAuditLogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/audit-log'
    | '/business'
    | '/rbac'
    | '/user-management'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/audit-log/$role'
    | '/business/history'
    | '/business/plan'
    | '/business/subscription'
    | '/rbac/module'
    | '/rbac/permission'
    | '/rbac/role'
    | '/service/other'
    | '/service/requests'
    | '/user-management/admin'
    | '/user-management/agency'
    | '/user-management/outlet'
    | '/user-management/pr'
    | '/audit-log/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/business'
    | '/rbac'
    | '/user-management'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/audit-log/$role'
    | '/business/history'
    | '/business/plan'
    | '/business/subscription'
    | '/rbac/module'
    | '/rbac/permission'
    | '/rbac/role'
    | '/service/other'
    | '/service/requests'
    | '/user-management/admin'
    | '/user-management/agency'
    | '/user-management/outlet'
    | '/user-management/pr'
    | '/audit-log'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/(admin)/audit-log'
    | '/(admin)/business'
    | '/(admin)/rbac'
    | '/(admin)/user-management'
    | '/(admin)/dashboard'
    | '/(admin)/profile'
    | '/(admin)/settings'
    | '/(admin)/audit-log/$role'
    | '/(admin)/business/history'
    | '/(admin)/business/plan'
    | '/(admin)/business/subscription'
    | '/(admin)/rbac/module'
    | '/(admin)/rbac/permission'
    | '/(admin)/rbac/role'
    | '/(admin)/service/other'
    | '/(admin)/service/requests'
    | '/(admin)/user-management/admin'
    | '/(admin)/user-management/agency'
    | '/(admin)/user-management/outlet'
    | '/(admin)/user-management/pr'
    | '/(admin)/audit-log/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminRouteRoute: typeof adminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/settings': {
      id: '/(admin)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof adminSettingsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/profile': {
      id: '/(admin)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof adminProfileRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/dashboard': {
      id: '/(admin)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof adminDashboardRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/user-management': {
      id: '/(admin)/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof adminUserManagementRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/rbac': {
      id: '/(admin)/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof adminRbacRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/business': {
      id: '/(admin)/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof adminBusinessRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/audit-log': {
      id: '/(admin)/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof adminAuditLogRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/audit-log/': {
      id: '/(admin)/audit-log/'
      path: '/'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof adminAuditLogIndexRouteImport
      parentRoute: typeof adminAuditLogRouteRoute
    }
    '/(admin)/user-management/pr': {
      id: '/(admin)/user-management/pr'
      path: '/pr'
      fullPath: '/user-management/pr'
      preLoaderRoute: typeof adminUserManagementPrRouteImport
      parentRoute: typeof adminUserManagementRouteRoute
    }
    '/(admin)/user-management/outlet': {
      id: '/(admin)/user-management/outlet'
      path: '/outlet'
      fullPath: '/user-management/outlet'
      preLoaderRoute: typeof adminUserManagementOutletRouteImport
      parentRoute: typeof adminUserManagementRouteRoute
    }
    '/(admin)/user-management/agency': {
      id: '/(admin)/user-management/agency'
      path: '/agency'
      fullPath: '/user-management/agency'
      preLoaderRoute: typeof adminUserManagementAgencyRouteImport
      parentRoute: typeof adminUserManagementRouteRoute
    }
    '/(admin)/user-management/admin': {
      id: '/(admin)/user-management/admin'
      path: '/admin'
      fullPath: '/user-management/admin'
      preLoaderRoute: typeof adminUserManagementAdminRouteImport
      parentRoute: typeof adminUserManagementRouteRoute
    }
    '/(admin)/service/requests': {
      id: '/(admin)/service/requests'
      path: '/service/requests'
      fullPath: '/service/requests'
      preLoaderRoute: typeof adminServiceRequestsRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/service/other': {
      id: '/(admin)/service/other'
      path: '/service/other'
      fullPath: '/service/other'
      preLoaderRoute: typeof adminServiceOtherRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/rbac/role': {
      id: '/(admin)/rbac/role'
      path: '/role'
      fullPath: '/rbac/role'
      preLoaderRoute: typeof adminRbacRoleRouteImport
      parentRoute: typeof adminRbacRouteRoute
    }
    '/(admin)/rbac/permission': {
      id: '/(admin)/rbac/permission'
      path: '/permission'
      fullPath: '/rbac/permission'
      preLoaderRoute: typeof adminRbacPermissionRouteImport
      parentRoute: typeof adminRbacRouteRoute
    }
    '/(admin)/rbac/module': {
      id: '/(admin)/rbac/module'
      path: '/module'
      fullPath: '/rbac/module'
      preLoaderRoute: typeof adminRbacModuleRouteImport
      parentRoute: typeof adminRbacRouteRoute
    }
    '/(admin)/business/subscription': {
      id: '/(admin)/business/subscription'
      path: '/subscription'
      fullPath: '/business/subscription'
      preLoaderRoute: typeof adminBusinessSubscriptionRouteImport
      parentRoute: typeof adminBusinessRouteRoute
    }
    '/(admin)/business/plan': {
      id: '/(admin)/business/plan'
      path: '/plan'
      fullPath: '/business/plan'
      preLoaderRoute: typeof adminBusinessPlanRouteImport
      parentRoute: typeof adminBusinessRouteRoute
    }
    '/(admin)/business/history': {
      id: '/(admin)/business/history'
      path: '/history'
      fullPath: '/business/history'
      preLoaderRoute: typeof adminBusinessHistoryRouteImport
      parentRoute: typeof adminBusinessRouteRoute
    }
    '/(admin)/audit-log/$role': {
      id: '/(admin)/audit-log/$role'
      path: '/$role'
      fullPath: '/audit-log/$role'
      preLoaderRoute: typeof adminAuditLogRoleRouteImport
      parentRoute: typeof adminAuditLogRouteRoute
    }
  }
}

interface adminAuditLogRouteRouteChildren {
  adminAuditLogRoleRoute: typeof adminAuditLogRoleRoute
  adminAuditLogIndexRoute: typeof adminAuditLogIndexRoute
}

const adminAuditLogRouteRouteChildren: adminAuditLogRouteRouteChildren = {
  adminAuditLogRoleRoute: adminAuditLogRoleRoute,
  adminAuditLogIndexRoute: adminAuditLogIndexRoute,
}

const adminAuditLogRouteRouteWithChildren =
  adminAuditLogRouteRoute._addFileChildren(adminAuditLogRouteRouteChildren)

interface adminBusinessRouteRouteChildren {
  adminBusinessHistoryRoute: typeof adminBusinessHistoryRoute
  adminBusinessPlanRoute: typeof adminBusinessPlanRoute
  adminBusinessSubscriptionRoute: typeof adminBusinessSubscriptionRoute
}

const adminBusinessRouteRouteChildren: adminBusinessRouteRouteChildren = {
  adminBusinessHistoryRoute: adminBusinessHistoryRoute,
  adminBusinessPlanRoute: adminBusinessPlanRoute,
  adminBusinessSubscriptionRoute: adminBusinessSubscriptionRoute,
}

const adminBusinessRouteRouteWithChildren =
  adminBusinessRouteRoute._addFileChildren(adminBusinessRouteRouteChildren)

interface adminRbacRouteRouteChildren {
  adminRbacModuleRoute: typeof adminRbacModuleRoute
  adminRbacPermissionRoute: typeof adminRbacPermissionRoute
  adminRbacRoleRoute: typeof adminRbacRoleRoute
}

const adminRbacRouteRouteChildren: adminRbacRouteRouteChildren = {
  adminRbacModuleRoute: adminRbacModuleRoute,
  adminRbacPermissionRoute: adminRbacPermissionRoute,
  adminRbacRoleRoute: adminRbacRoleRoute,
}

const adminRbacRouteRouteWithChildren = adminRbacRouteRoute._addFileChildren(
  adminRbacRouteRouteChildren,
)

interface adminUserManagementRouteRouteChildren {
  adminUserManagementAdminRoute: typeof adminUserManagementAdminRoute
  adminUserManagementAgencyRoute: typeof adminUserManagementAgencyRoute
  adminUserManagementOutletRoute: typeof adminUserManagementOutletRoute
  adminUserManagementPrRoute: typeof adminUserManagementPrRoute
}

const adminUserManagementRouteRouteChildren: adminUserManagementRouteRouteChildren =
  {
    adminUserManagementAdminRoute: adminUserManagementAdminRoute,
    adminUserManagementAgencyRoute: adminUserManagementAgencyRoute,
    adminUserManagementOutletRoute: adminUserManagementOutletRoute,
    adminUserManagementPrRoute: adminUserManagementPrRoute,
  }

const adminUserManagementRouteRouteWithChildren =
  adminUserManagementRouteRoute._addFileChildren(
    adminUserManagementRouteRouteChildren,
  )

interface adminRouteRouteChildren {
  adminAuditLogRouteRoute: typeof adminAuditLogRouteRouteWithChildren
  adminBusinessRouteRoute: typeof adminBusinessRouteRouteWithChildren
  adminRbacRouteRoute: typeof adminRbacRouteRouteWithChildren
  adminUserManagementRouteRoute: typeof adminUserManagementRouteRouteWithChildren
  adminDashboardRoute: typeof adminDashboardRoute
  adminProfileRoute: typeof adminProfileRoute
  adminSettingsRoute: typeof adminSettingsRoute
  adminServiceOtherRoute: typeof adminServiceOtherRoute
  adminServiceRequestsRoute: typeof adminServiceRequestsRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAuditLogRouteRoute: adminAuditLogRouteRouteWithChildren,
  adminBusinessRouteRoute: adminBusinessRouteRouteWithChildren,
  adminRbacRouteRoute: adminRbacRouteRouteWithChildren,
  adminUserManagementRouteRoute: adminUserManagementRouteRouteWithChildren,
  adminDashboardRoute: adminDashboardRoute,
  adminProfileRoute: adminProfileRoute,
  adminSettingsRoute: adminSettingsRoute,
  adminServiceOtherRoute: adminServiceOtherRoute,
  adminServiceRequestsRoute: adminServiceRequestsRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminRouteRoute: adminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
