/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgencyRouteRouteImport } from './routes/agency/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OutletDashboardRouteImport } from './routes/outlet/dashboard'
import { Route as AgencyDashboardRouteImport } from './routes/agency/dashboard'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminUserManagementRouteRouteImport } from './routes/admin/user-management/route'
import { Route as AdminRbacRouteRouteImport } from './routes/admin/rbac/route'
import { Route as AdminBusinessRouteRouteImport } from './routes/admin/business/route'
import { Route as AdminAuditLogRouteRouteImport } from './routes/admin/audit-log/route'
import { Route as AdminAuditLogIndexRouteImport } from './routes/admin/audit-log/index'
import { Route as AdminUserManagementPrRouteImport } from './routes/admin/user-management/pr'
import { Route as AdminUserManagementOutletRouteImport } from './routes/admin/user-management/outlet'
import { Route as AdminUserManagementAgencyRouteImport } from './routes/admin/user-management/agency'
import { Route as AdminUserManagementAdminRouteImport } from './routes/admin/user-management/admin'
import { Route as AdminServiceRequestsRouteImport } from './routes/admin/service/requests'
import { Route as AdminServiceOtherRouteImport } from './routes/admin/service/other'
import { Route as AdminRbacRoleRouteImport } from './routes/admin/rbac/role'
import { Route as AdminRbacPermissionRouteImport } from './routes/admin/rbac/permission'
import { Route as AdminRbacPendingRouteImport } from './routes/admin/rbac/pending'
import { Route as AdminRbacModuleRouteImport } from './routes/admin/rbac/module'
import { Route as AdminBusinessSubscriptionRouteImport } from './routes/admin/business/subscription'
import { Route as AdminBusinessPlanRouteImport } from './routes/admin/business/plan'
import { Route as AdminBusinessHistoryRouteImport } from './routes/admin/business/history'
import { Route as AdminAuditLogRoleRouteImport } from './routes/admin/audit-log/$role'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRouteRoute = AgencyRouteRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OutletDashboardRoute = OutletDashboardRouteImport.update({
  id: '/outlet/dashboard',
  path: '/outlet/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyDashboardRoute = AgencyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgencyRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUserManagementRouteRoute =
  AdminUserManagementRouteRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRbacRouteRoute = AdminRbacRouteRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBusinessRouteRoute = AdminBusinessRouteRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRouteRoute = AdminAuditLogRouteRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogIndexRoute = AdminAuditLogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuditLogRouteRoute,
} as any)
const AdminUserManagementPrRoute = AdminUserManagementPrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => AdminUserManagementRouteRoute,
} as any)
const AdminUserManagementOutletRoute =
  AdminUserManagementOutletRouteImport.update({
    id: '/outlet',
    path: '/outlet',
    getParentRoute: () => AdminUserManagementRouteRoute,
  } as any)
const AdminUserManagementAgencyRoute =
  AdminUserManagementAgencyRouteImport.update({
    id: '/agency',
    path: '/agency',
    getParentRoute: () => AdminUserManagementRouteRoute,
  } as any)
const AdminUserManagementAdminRoute =
  AdminUserManagementAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AdminUserManagementRouteRoute,
  } as any)
const AdminServiceRequestsRoute = AdminServiceRequestsRouteImport.update({
  id: '/service/requests',
  path: '/service/requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServiceOtherRoute = AdminServiceOtherRouteImport.update({
  id: '/service/other',
  path: '/service/other',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRbacRoleRoute = AdminRbacRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AdminRbacRouteRoute,
} as any)
const AdminRbacPermissionRoute = AdminRbacPermissionRouteImport.update({
  id: '/permission',
  path: '/permission',
  getParentRoute: () => AdminRbacRouteRoute,
} as any)
const AdminRbacPendingRoute = AdminRbacPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminRbacRouteRoute,
} as any)
const AdminRbacModuleRoute = AdminRbacModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => AdminRbacRouteRoute,
} as any)
const AdminBusinessSubscriptionRoute =
  AdminBusinessSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AdminBusinessRouteRoute,
  } as any)
const AdminBusinessPlanRoute = AdminBusinessPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AdminBusinessRouteRoute,
} as any)
const AdminBusinessHistoryRoute = AdminBusinessHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminBusinessRouteRoute,
} as any)
const AdminAuditLogRoleRoute = AdminAuditLogRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => AdminAuditLogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agency': typeof AgencyRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/admin/audit-log': typeof AdminAuditLogRouteRouteWithChildren
  '/admin/business': typeof AdminBusinessRouteRouteWithChildren
  '/admin/rbac': typeof AdminRbacRouteRouteWithChildren
  '/admin/user-management': typeof AdminUserManagementRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/outlet/dashboard': typeof OutletDashboardRoute
  '/admin/audit-log/$role': typeof AdminAuditLogRoleRoute
  '/admin/business/history': typeof AdminBusinessHistoryRoute
  '/admin/business/plan': typeof AdminBusinessPlanRoute
  '/admin/business/subscription': typeof AdminBusinessSubscriptionRoute
  '/admin/rbac/module': typeof AdminRbacModuleRoute
  '/admin/rbac/pending': typeof AdminRbacPendingRoute
  '/admin/rbac/permission': typeof AdminRbacPermissionRoute
  '/admin/rbac/role': typeof AdminRbacRoleRoute
  '/admin/service/other': typeof AdminServiceOtherRoute
  '/admin/service/requests': typeof AdminServiceRequestsRoute
  '/admin/user-management/admin': typeof AdminUserManagementAdminRoute
  '/admin/user-management/agency': typeof AdminUserManagementAgencyRoute
  '/admin/user-management/outlet': typeof AdminUserManagementOutletRoute
  '/admin/user-management/pr': typeof AdminUserManagementPrRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agency': typeof AgencyRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/admin/business': typeof AdminBusinessRouteRouteWithChildren
  '/admin/rbac': typeof AdminRbacRouteRouteWithChildren
  '/admin/user-management': typeof AdminUserManagementRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/outlet/dashboard': typeof OutletDashboardRoute
  '/admin/audit-log/$role': typeof AdminAuditLogRoleRoute
  '/admin/business/history': typeof AdminBusinessHistoryRoute
  '/admin/business/plan': typeof AdminBusinessPlanRoute
  '/admin/business/subscription': typeof AdminBusinessSubscriptionRoute
  '/admin/rbac/module': typeof AdminRbacModuleRoute
  '/admin/rbac/pending': typeof AdminRbacPendingRoute
  '/admin/rbac/permission': typeof AdminRbacPermissionRoute
  '/admin/rbac/role': typeof AdminRbacRoleRoute
  '/admin/service/other': typeof AdminServiceOtherRoute
  '/admin/service/requests': typeof AdminServiceRequestsRoute
  '/admin/user-management/admin': typeof AdminUserManagementAdminRoute
  '/admin/user-management/agency': typeof AdminUserManagementAgencyRoute
  '/admin/user-management/outlet': typeof AdminUserManagementOutletRoute
  '/admin/user-management/pr': typeof AdminUserManagementPrRoute
  '/admin/audit-log': typeof AdminAuditLogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/agency': typeof AgencyRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/admin/audit-log': typeof AdminAuditLogRouteRouteWithChildren
  '/admin/business': typeof AdminBusinessRouteRouteWithChildren
  '/admin/rbac': typeof AdminRbacRouteRouteWithChildren
  '/admin/user-management': typeof AdminUserManagementRouteRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/agency/dashboard': typeof AgencyDashboardRoute
  '/outlet/dashboard': typeof OutletDashboardRoute
  '/admin/audit-log/$role': typeof AdminAuditLogRoleRoute
  '/admin/business/history': typeof AdminBusinessHistoryRoute
  '/admin/business/plan': typeof AdminBusinessPlanRoute
  '/admin/business/subscription': typeof AdminBusinessSubscriptionRoute
  '/admin/rbac/module': typeof AdminRbacModuleRoute
  '/admin/rbac/pending': typeof AdminRbacPendingRoute
  '/admin/rbac/permission': typeof AdminRbacPermissionRoute
  '/admin/rbac/role': typeof AdminRbacRoleRoute
  '/admin/service/other': typeof AdminServiceOtherRoute
  '/admin/service/requests': typeof AdminServiceRequestsRoute
  '/admin/user-management/admin': typeof AdminUserManagementAdminRoute
  '/admin/user-management/agency': typeof AdminUserManagementAgencyRoute
  '/admin/user-management/outlet': typeof AdminUserManagementOutletRoute
  '/admin/user-management/pr': typeof AdminUserManagementPrRoute
  '/admin/audit-log/': typeof AdminAuditLogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agency'
    | '/login'
    | '/no-access'
    | '/not-found'
    | '/signup'
    | '/admin/audit-log'
    | '/admin/business'
    | '/admin/rbac'
    | '/admin/user-management'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/settings'
    | '/agency/dashboard'
    | '/outlet/dashboard'
    | '/admin/audit-log/$role'
    | '/admin/business/history'
    | '/admin/business/plan'
    | '/admin/business/subscription'
    | '/admin/rbac/module'
    | '/admin/rbac/pending'
    | '/admin/rbac/permission'
    | '/admin/rbac/role'
    | '/admin/service/other'
    | '/admin/service/requests'
    | '/admin/user-management/admin'
    | '/admin/user-management/agency'
    | '/admin/user-management/outlet'
    | '/admin/user-management/pr'
    | '/admin/audit-log/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agency'
    | '/login'
    | '/no-access'
    | '/not-found'
    | '/signup'
    | '/admin/business'
    | '/admin/rbac'
    | '/admin/user-management'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/settings'
    | '/agency/dashboard'
    | '/outlet/dashboard'
    | '/admin/audit-log/$role'
    | '/admin/business/history'
    | '/admin/business/plan'
    | '/admin/business/subscription'
    | '/admin/rbac/module'
    | '/admin/rbac/pending'
    | '/admin/rbac/permission'
    | '/admin/rbac/role'
    | '/admin/service/other'
    | '/admin/service/requests'
    | '/admin/user-management/admin'
    | '/admin/user-management/agency'
    | '/admin/user-management/outlet'
    | '/admin/user-management/pr'
    | '/admin/audit-log'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agency'
    | '/login'
    | '/no-access'
    | '/not-found'
    | '/signup'
    | '/admin/audit-log'
    | '/admin/business'
    | '/admin/rbac'
    | '/admin/user-management'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/settings'
    | '/agency/dashboard'
    | '/outlet/dashboard'
    | '/admin/audit-log/$role'
    | '/admin/business/history'
    | '/admin/business/plan'
    | '/admin/business/subscription'
    | '/admin/rbac/module'
    | '/admin/rbac/pending'
    | '/admin/rbac/permission'
    | '/admin/rbac/role'
    | '/admin/service/other'
    | '/admin/service/requests'
    | '/admin/user-management/admin'
    | '/admin/user-management/agency'
    | '/admin/user-management/outlet'
    | '/admin/user-management/pr'
    | '/admin/audit-log/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AgencyRouteRoute: typeof AgencyRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  NotFoundRoute: typeof NotFoundRoute
  SignupRoute: typeof SignupRoute
  OutletDashboardRoute: typeof OutletDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlet/dashboard': {
      id: '/outlet/dashboard'
      path: '/outlet/dashboard'
      fullPath: '/outlet/dashboard'
      preLoaderRoute: typeof OutletDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/dashboard': {
      id: '/agency/dashboard'
      path: '/dashboard'
      fullPath: '/agency/dashboard'
      preLoaderRoute: typeof AgencyDashboardRouteImport
      parentRoute: typeof AgencyRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/business': {
      id: '/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AdminBusinessRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log/': {
      id: '/admin/audit-log/'
      path: '/'
      fullPath: '/admin/audit-log/'
      preLoaderRoute: typeof AdminAuditLogIndexRouteImport
      parentRoute: typeof AdminAuditLogRouteRoute
    }
    '/admin/user-management/pr': {
      id: '/admin/user-management/pr'
      path: '/pr'
      fullPath: '/admin/user-management/pr'
      preLoaderRoute: typeof AdminUserManagementPrRouteImport
      parentRoute: typeof AdminUserManagementRouteRoute
    }
    '/admin/user-management/outlet': {
      id: '/admin/user-management/outlet'
      path: '/outlet'
      fullPath: '/admin/user-management/outlet'
      preLoaderRoute: typeof AdminUserManagementOutletRouteImport
      parentRoute: typeof AdminUserManagementRouteRoute
    }
    '/admin/user-management/agency': {
      id: '/admin/user-management/agency'
      path: '/agency'
      fullPath: '/admin/user-management/agency'
      preLoaderRoute: typeof AdminUserManagementAgencyRouteImport
      parentRoute: typeof AdminUserManagementRouteRoute
    }
    '/admin/user-management/admin': {
      id: '/admin/user-management/admin'
      path: '/admin'
      fullPath: '/admin/user-management/admin'
      preLoaderRoute: typeof AdminUserManagementAdminRouteImport
      parentRoute: typeof AdminUserManagementRouteRoute
    }
    '/admin/service/requests': {
      id: '/admin/service/requests'
      path: '/service/requests'
      fullPath: '/admin/service/requests'
      preLoaderRoute: typeof AdminServiceRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/service/other': {
      id: '/admin/service/other'
      path: '/service/other'
      fullPath: '/admin/service/other'
      preLoaderRoute: typeof AdminServiceOtherRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rbac/role': {
      id: '/admin/rbac/role'
      path: '/role'
      fullPath: '/admin/rbac/role'
      preLoaderRoute: typeof AdminRbacRoleRouteImport
      parentRoute: typeof AdminRbacRouteRoute
    }
    '/admin/rbac/permission': {
      id: '/admin/rbac/permission'
      path: '/permission'
      fullPath: '/admin/rbac/permission'
      preLoaderRoute: typeof AdminRbacPermissionRouteImport
      parentRoute: typeof AdminRbacRouteRoute
    }
    '/admin/rbac/pending': {
      id: '/admin/rbac/pending'
      path: '/pending'
      fullPath: '/admin/rbac/pending'
      preLoaderRoute: typeof AdminRbacPendingRouteImport
      parentRoute: typeof AdminRbacRouteRoute
    }
    '/admin/rbac/module': {
      id: '/admin/rbac/module'
      path: '/module'
      fullPath: '/admin/rbac/module'
      preLoaderRoute: typeof AdminRbacModuleRouteImport
      parentRoute: typeof AdminRbacRouteRoute
    }
    '/admin/business/subscription': {
      id: '/admin/business/subscription'
      path: '/subscription'
      fullPath: '/admin/business/subscription'
      preLoaderRoute: typeof AdminBusinessSubscriptionRouteImport
      parentRoute: typeof AdminBusinessRouteRoute
    }
    '/admin/business/plan': {
      id: '/admin/business/plan'
      path: '/plan'
      fullPath: '/admin/business/plan'
      preLoaderRoute: typeof AdminBusinessPlanRouteImport
      parentRoute: typeof AdminBusinessRouteRoute
    }
    '/admin/business/history': {
      id: '/admin/business/history'
      path: '/history'
      fullPath: '/admin/business/history'
      preLoaderRoute: typeof AdminBusinessHistoryRouteImport
      parentRoute: typeof AdminBusinessRouteRoute
    }
    '/admin/audit-log/$role': {
      id: '/admin/audit-log/$role'
      path: '/$role'
      fullPath: '/admin/audit-log/$role'
      preLoaderRoute: typeof AdminAuditLogRoleRouteImport
      parentRoute: typeof AdminAuditLogRouteRoute
    }
  }
}

interface AdminAuditLogRouteRouteChildren {
  AdminAuditLogRoleRoute: typeof AdminAuditLogRoleRoute
  AdminAuditLogIndexRoute: typeof AdminAuditLogIndexRoute
}

const AdminAuditLogRouteRouteChildren: AdminAuditLogRouteRouteChildren = {
  AdminAuditLogRoleRoute: AdminAuditLogRoleRoute,
  AdminAuditLogIndexRoute: AdminAuditLogIndexRoute,
}

const AdminAuditLogRouteRouteWithChildren =
  AdminAuditLogRouteRoute._addFileChildren(AdminAuditLogRouteRouteChildren)

interface AdminBusinessRouteRouteChildren {
  AdminBusinessHistoryRoute: typeof AdminBusinessHistoryRoute
  AdminBusinessPlanRoute: typeof AdminBusinessPlanRoute
  AdminBusinessSubscriptionRoute: typeof AdminBusinessSubscriptionRoute
}

const AdminBusinessRouteRouteChildren: AdminBusinessRouteRouteChildren = {
  AdminBusinessHistoryRoute: AdminBusinessHistoryRoute,
  AdminBusinessPlanRoute: AdminBusinessPlanRoute,
  AdminBusinessSubscriptionRoute: AdminBusinessSubscriptionRoute,
}

const AdminBusinessRouteRouteWithChildren =
  AdminBusinessRouteRoute._addFileChildren(AdminBusinessRouteRouteChildren)

interface AdminRbacRouteRouteChildren {
  AdminRbacModuleRoute: typeof AdminRbacModuleRoute
  AdminRbacPendingRoute: typeof AdminRbacPendingRoute
  AdminRbacPermissionRoute: typeof AdminRbacPermissionRoute
  AdminRbacRoleRoute: typeof AdminRbacRoleRoute
}

const AdminRbacRouteRouteChildren: AdminRbacRouteRouteChildren = {
  AdminRbacModuleRoute: AdminRbacModuleRoute,
  AdminRbacPendingRoute: AdminRbacPendingRoute,
  AdminRbacPermissionRoute: AdminRbacPermissionRoute,
  AdminRbacRoleRoute: AdminRbacRoleRoute,
}

const AdminRbacRouteRouteWithChildren = AdminRbacRouteRoute._addFileChildren(
  AdminRbacRouteRouteChildren,
)

interface AdminUserManagementRouteRouteChildren {
  AdminUserManagementAdminRoute: typeof AdminUserManagementAdminRoute
  AdminUserManagementAgencyRoute: typeof AdminUserManagementAgencyRoute
  AdminUserManagementOutletRoute: typeof AdminUserManagementOutletRoute
  AdminUserManagementPrRoute: typeof AdminUserManagementPrRoute
}

const AdminUserManagementRouteRouteChildren: AdminUserManagementRouteRouteChildren =
  {
    AdminUserManagementAdminRoute: AdminUserManagementAdminRoute,
    AdminUserManagementAgencyRoute: AdminUserManagementAgencyRoute,
    AdminUserManagementOutletRoute: AdminUserManagementOutletRoute,
    AdminUserManagementPrRoute: AdminUserManagementPrRoute,
  }

const AdminUserManagementRouteRouteWithChildren =
  AdminUserManagementRouteRoute._addFileChildren(
    AdminUserManagementRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminAuditLogRouteRoute: typeof AdminAuditLogRouteRouteWithChildren
  AdminBusinessRouteRoute: typeof AdminBusinessRouteRouteWithChildren
  AdminRbacRouteRoute: typeof AdminRbacRouteRouteWithChildren
  AdminUserManagementRouteRoute: typeof AdminUserManagementRouteRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminServiceOtherRoute: typeof AdminServiceOtherRoute
  AdminServiceRequestsRoute: typeof AdminServiceRequestsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogRouteRoute: AdminAuditLogRouteRouteWithChildren,
  AdminBusinessRouteRoute: AdminBusinessRouteRouteWithChildren,
  AdminRbacRouteRoute: AdminRbacRouteRouteWithChildren,
  AdminUserManagementRouteRoute: AdminUserManagementRouteRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminServiceOtherRoute: AdminServiceOtherRoute,
  AdminServiceRequestsRoute: AdminServiceRequestsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AgencyRouteRouteChildren {
  AgencyDashboardRoute: typeof AgencyDashboardRoute
}

const AgencyRouteRouteChildren: AgencyRouteRouteChildren = {
  AgencyDashboardRoute: AgencyDashboardRoute,
}

const AgencyRouteRouteWithChildren = AgencyRouteRoute._addFileChildren(
  AgencyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AgencyRouteRoute: AgencyRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  NotFoundRoute: NotFoundRoute,
  SignupRoute: SignupRoute,
  OutletDashboardRoute: OutletDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
