/**
 * Privacy Policy copy for the public web page at /privacy.
 */

export type PrivacySection = {
	id: string
	title: string
	paragraphs: string[]
	bullets?: string[]
}

export const PRIVACY_POLICY_EFFECTIVE_DATE = "4 August 2026"
export const PRIVACY_POLICY_LAST_UPDATED = "4 August 2026"
export const PRIVACY_CONTACT_WHATSAPP = "https://wa.me/60122190198"
export const PRIVACY_CONTACT_LABEL = "WhatsApp +60 12-219 0198"

export const privacyPolicyIntro =
	"InnocenZ (“we”, “us”, or “our”) operates the InnocenZ web portals and the InnocenZ PR mobile application (together, the “Services”). This Privacy Policy explains how we collect, use, disclose, store, and protect personal data when you use our Services as an Outlet, PR Agency, PR (promoter / host), or Admin."

export const privacyPolicySections: PrivacySection[] = [
	{
		id: "who",
		title: "1. Who this policy covers",
		paragraphs: [
			"This policy applies to anyone who creates an account, is invited onto the platform, or otherwise uses InnocenZ — including Outlet operators, agency staff, PR workforce members, and platform administrators. It also covers visitors to our public marketing website who contact us.",
		],
	},
	{
		id: "collect",
		title: "2. Personal data we collect",
		paragraphs: [
			"We collect personal data that you provide, that is generated by your use of the Services, and that we need to operate nightlife workforce workflows (rostering, attendance, receipts, and payouts).",
		],
		bullets: [
			"Account & identity: name, display / floor nickname, email address, mobile number, password (stored hashed), nationality, date of birth, and identity documents (for example NRIC, passport, or work permit numbers and related verification details).",
			"Profile & showcase: profile photo, portfolio / gallery photos, comcard image, height, weight, age, languages, and agency membership links.",
			"Business records (Outlet / Agency): company registration documents, business contacts, registered address, subscription and billing details.",
			"Work & payroll data: shifts and assignments, check-in / check-out times, proof photos, GPS / location used for geofenced attendance, scanned or self-logged receipts, commission and tips lines, payment vouchers, digital signatures, disputes, and overtime claims.",
			"Technical & security data: device and browser type, IP address, session tokens, login timestamps, and audit-log events related to account actions.",
			"Communications: WhatsApp or email one-time passwords (OTP), support messages you send us, and in-app notifications about shifts or payouts.",
		],
	},
	{
		id: "how",
		title: "3. How we use personal data",
		paragraphs: [
			"We use personal data only for purposes related to operating InnocenZ and complying with law, including:",
		],
		bullets: [
			"Creating and securing accounts, verifying mobile numbers or email, and preventing fraud or abuse.",
			"Matching Outlets, Agencies, and PRs for rostering, shift assignment, attendance, and on-floor operations.",
			"Calculating wages, commission, tips, overtime, and issuing / signing payment vouchers.",
			"Showing each role only the information they need (for example, a PR sees their own earnings, not upstream outlet or agency margins).",
			"Providing customer support, product updates, and service notices.",
			"Maintaining audit trails, resolving disputes, and meeting legal or regulatory obligations (including Malaysia’s Personal Data Protection Act 2010).",
			"Improving reliability, security, and performance of the Services.",
		],
	},
	{
		id: "share",
		title: "4. How we share personal data",
		paragraphs: [
			"We do not sell personal data. We share it only as needed to run the platform:",
		],
		bullets: [
			"Between linked roles: Outlets, Agencies, and PRs see limited profile and shift information required for booking, attendance, receipts, and payroll. Identity documents shown to Outlets are redacted where our product rules require it.",
			"Service providers: hosting, database, email / WhatsApp messaging, and similar processors who act on our instructions under appropriate safeguards.",
			"Legal & safety: when required by law, court order, or to protect the rights, safety, or integrity of InnocenZ users and the platform.",
			"Business transfers: if we undergo a merger, acquisition, or asset sale, personal data may transfer under continued confidentiality obligations.",
		],
	},
	{
		id: "location",
		title: "5. Location data",
		paragraphs: [
			"The PR mobile app may request device location to confirm check-in within an outlet geofence. Location is used for attendance verification and related operational records. You can deny location permission, but check-in features that require geofencing may not work.",
		],
	},
	{
		id: "retention",
		title: "6. Retention",
		paragraphs: [
			"We keep personal data for as long as your account remains active and as needed for payroll history, dispute resolution, audit, and legal retention. When you request account deletion, we remove or anonymise personal data that is no longer required, except where we must retain records (for example signed payment vouchers or statutory records).",
		],
	},
	{
		id: "security",
		title: "7. Security",
		paragraphs: [
			"We use industry-standard measures such as encrypted transport (HTTPS), hashed passwords, role-based access controls, and server-side session authentication. No method of transmission or storage is completely secure; please protect your login credentials and notify us promptly of any suspected unauthorised access.",
		],
	},
	{
		id: "rights",
		title: "8. Your rights",
		paragraphs: [
			"Subject to applicable law (including the PDPA), you may request access to, correction of, or deletion of your personal data, withdraw consent where processing is consent-based, or limit certain processing. You can update much of your profile data in-app. For other requests, contact us using the details below. We may need to verify your identity before fulfilling a request.",
		],
	},
	{
		id: "children",
		title: "9. Children",
		paragraphs: [
			"InnocenZ is intended for adults working in nightlife operations. We do not knowingly collect personal data from children under 18. If you believe a minor has provided data, contact us and we will take appropriate steps.",
		],
	},
	{
		id: "transfers",
		title: "10. International transfers",
		paragraphs: [
			"Our Services are operated primarily for users in Malaysia and neighbouring markets. If personal data is processed or stored outside Malaysia, we take steps reasonably necessary to ensure it remains protected in line with this policy and applicable law.",
		],
	},
	{
		id: "changes",
		title: "11. Changes to this policy",
		paragraphs: [
			"We may update this Privacy Policy from time to time. The “Last updated” date at the top of the page will change when we do. Continued use of the Services after an update constitutes acceptance of the revised policy, except where applicable law requires additional notice or consent.",
		],
	},
	{
		id: "contact",
		title: "12. Contact us",
		paragraphs: [
			"For privacy questions, access or deletion requests, or complaints about how we handle personal data, contact InnocenZ support via WhatsApp at +60 12-219 0198. We will respond within a reasonable time.",
		],
	},
]
