// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Written by `node tools/scripts/sync-rbac-matrix.mjs` from the live
// `role_permission` table. The database is the RBAC authority (owner's rule,
// 11 Sep 2026: "web matrix must follow what database given"), and the server
// reads the SAME rows through `requirePermission` → `roleHasPermission`, so
// what is listed here is what the API will actually allow.
//
// Each entry is that lane's grants as `module_key:permission_type`. The
// portals turn these into their own permission names through
// OUTLET_FEATURE_MODULE / AGENCY_FEATURE_MODULE — that mapping stays in
// TypeScript so this file is pure data.
//
// ⚠️ Editing this file changes nothing durable: the next sync overwrites it and
// `--check` fails while it disagrees with the database. To change what a role
// may do, change `role_permission` and re-run the sync.

export const OUTLET_ROLE_GRANTS = {
	outlet_owner: [
		"billing:read",
		"booking:create",
		"booking:read",
		"booking:update",
		"dashboard:read",
		"history:read",
		"rating:create",
		"rating:read",
		"rating:update",
		"sales:create",
		"sales:read",
		"sales:update",
		"settings:create",
		"settings:read",
		"settings:update",
		"special_service:create",
		"special_service:read",
		"special_service:update",
		"workspace:create",
		"workspace:read",
		"workspace:update",
	],
	outlet_guarantor: [
		"billing:read",
		"booking:create",
		"booking:read",
		"booking:update",
		"dashboard:read",
		"history:read",
		"rating:create",
		"rating:read",
		"rating:update",
		"sales:create",
		"sales:read",
		"sales:update",
		"settings:create",
		"settings:read",
		"settings:update",
		"special_service:create",
		"special_service:read",
		"special_service:update",
		"workspace:create",
		"workspace:read",
		"workspace:update",
	],
	outlet_director: [
		"billing:read",
		"booking:read",
		"dashboard:read",
		"history:read",
		"rating:read",
		"sales:read",
		"settings:read",
		"workspace:read",
	],
	outlet_finance: [
		"billing:read",
		"booking:create",
		"booking:read",
		"booking:update",
		"dashboard:read",
		"history:read",
		"rating:create",
		"rating:read",
		"rating:update",
		"sales:create",
		"sales:read",
		"sales:update",
		"settings:read",
		"special_service:create",
		"special_service:read",
		"special_service:update",
		"workspace:create",
		"workspace:read",
		"workspace:update",
	],
	outlet_ops: [
		"booking:create",
		"booking:read",
		"booking:update",
		"dashboard:read",
		"history:read",
		"rating:create",
		"rating:read",
		"rating:update",
		"sales:create",
		"sales:read",
		"sales:update",
		"settings:read",
		"special_service:create",
		"special_service:read",
		"special_service:update",
		"workspace:create",
		"workspace:read",
		"workspace:update",
	],
} as const;

export const AGENCY_ROLE_GRANTS = {
	agency_owner: [
		"approvals:create",
		"approvals:read",
		"approvals:update",
		"collections:read",
		"collections:update",
		"dashboard:read",
		"history:read",
		"payment_voucher:create",
		"payment_voucher:read",
		"payment_voucher:update",
		"roster:create",
		"roster:read",
		"roster:update",
		"settings:create",
		"settings:read",
		"settings:update",
		"workforce:create",
		"workforce:read",
		"workforce:update",
	],
	agency_guarantor: [
		"approvals:create",
		"approvals:read",
		"approvals:update",
		"collections:read",
		"collections:update",
		"dashboard:read",
		"history:read",
		"payment_voucher:create",
		"payment_voucher:read",
		"payment_voucher:update",
		"roster:create",
		"roster:read",
		"roster:update",
		"settings:create",
		"settings:read",
		"settings:update",
		"workforce:create",
		"workforce:read",
		"workforce:update",
	],
	agency_director: [
		"approvals:read",
		"collections:read",
		"dashboard:read",
		"history:read",
		"payment_voucher:read",
		"roster:read",
		"settings:read",
		"workforce:read",
	],
	agency_finance: [
		"collections:read",
		"collections:update",
		"dashboard:read",
		"history:read",
		"payment_voucher:create",
		"payment_voucher:read",
		"payment_voucher:update",
		"settings:read",
		"workforce:read",
	],
} as const;
